name: Automatic Deploy for Ennil Site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      - ubuntu-latest
      - node version 20

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-verion: ${{matrix.node-version}}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test